-- Agente DB schema reference
-- This file documents the current logical structure used by the app.
-- Keep it in sync with the backend repository files.

-- =========================================================
-- ops_usuarios
-- Source: src/modules/auth/auth.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- nombre VARCHAR(140) NOT NULL
-- email VARCHAR(190) NOT NULL UNIQUE
-- password_salt VARCHAR(128) NOT NULL
-- password_hash VARCHAR(255) NOT NULL
-- role VARCHAR(20) NOT NULL DEFAULT 'operario'
-- estado VARCHAR(20) NOT NULL DEFAULT 'activo'
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- =========================================================
-- ops_clientes
-- Source: src/modules/clients/client.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- nombre VARCHAR(140) NOT NULL
-- saldo DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- entregas_count INT NOT NULL DEFAULT 0
-- ultima_fecha_pago DATE NOT NULL
-- fecha_vencimiento DATE NOT NULL
-- estado VARCHAR(20) NOT NULL DEFAULT 'activo'
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

-- =========================================================
-- ops_clientes_historial
-- Source: src/modules/clients/client.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- client_id INT NOT NULL
-- tipo VARCHAR(20) NOT NULL
-- fecha_movimiento DATE NOT NULL
-- articulo VARCHAR(190) NOT NULL
-- cantidad INT NOT NULL DEFAULT 1
-- precio_unitario DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- detalle VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_client_fecha (client_id, fecha_movimiento)
-- FOREIGN KEY (client_id) REFERENCES ops_clientes(id) ON DELETE CASCADE

-- =========================================================
-- ops_cajas
-- Source: src/modules/caja/caja.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- opening_amount DECIMAL(12,2) NOT NULL
-- sales_total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- payments_total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
-- closed_at DATETIME NULL
-- opened_by_user_id INT NULL
-- opened_by_name VARCHAR(140) NOT NULL
-- opened_by_role VARCHAR(20) NOT NULL
-- status VARCHAR(20) NOT NULL DEFAULT 'open'
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_cajas_status_opened_at (status, opened_at)
-- INDEX idx_cajas_opened_by (opened_by_user_id, opened_at)

-- =========================================================
-- ops_caja_movimientos
-- Source: src/modules/caja/caja.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- caja_id INT NOT NULL
-- type VARCHAR(20) NOT NULL
-- amount DECIMAL(12,2) NOT NULL
-- description VARCHAR(255) NULL
-- source VARCHAR(40) NOT NULL DEFAULT 'manual'
-- operator_id INT NULL
-- operator_name VARCHAR(140) NULL
-- operator_role VARCHAR(20) NULL
-- metadata LONGTEXT NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_caja_movimientos_caja_fecha (caja_id, created_at)
-- INDEX idx_caja_movimientos_type_fecha (type, created_at)
-- FOREIGN KEY (caja_id) REFERENCES ops_cajas(id) ON DELETE CASCADE

-- =========================================================
-- ops_caja_movimiento_items
-- Source: src/modules/caja/caja.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- movement_id INT NOT NULL
-- barcode VARCHAR(120) NULL
-- product_name VARCHAR(190) NOT NULL
-- quantity INT NOT NULL DEFAULT 1
-- unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_caja_items_movement (movement_id)
-- FOREIGN KEY (movement_id) REFERENCES ops_caja_movimientos(id) ON DELETE CASCADE

-- =========================================================
-- ops_gastos
-- Source: src/modules/gastos/gastos.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- name VARCHAR(160) NOT NULL
-- amount DECIMAL(12,2) NOT NULL
-- frequency VARCHAR(20) NOT NULL DEFAULT 'monthly'
-- scope VARCHAR(20) NOT NULL DEFAULT 'business'
-- active TINYINT(1) NOT NULL DEFAULT 1
-- notes VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_gastos_active_scope (active, scope)
-- INDEX idx_gastos_frequency (frequency)

-- =========================================================
-- ops_stock_control
-- Source: src/modules/stock/stock.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- product_id INT NOT NULL UNIQUE
-- active TINYINT(1) NOT NULL DEFAULT 1
-- is_test_data TINYINT(1) NOT NULL DEFAULT 0
-- supplier_name VARCHAR(140) NULL
-- order_days_csv VARCHAR(80) NULL
-- delivery_days_csv VARCHAR(80) NULL
-- critical_threshold INT NOT NULL DEFAULT 1
-- warning_threshold INT NOT NULL DEFAULT 4
-- target_leftover INT NOT NULL DEFAULT 2
-- notes VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_stock_control_active (active)

-- =========================================================
-- ops_stock_movimientos
-- Source: src/modules/stock/stock.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- product_id INT NOT NULL
-- stock_control_id INT NULL
-- type VARCHAR(20) NOT NULL
-- quantity_delta INT NOT NULL
-- quantity_before INT NOT NULL
-- quantity_after INT NOT NULL
-- reference_type VARCHAR(40) NULL
-- reference_id BIGINT NULL
-- notes VARCHAR(255) NULL
-- operator_id INT NULL
-- operator_name VARCHAR(140) NULL
-- operator_role VARCHAR(20) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_stock_mov_product_date (product_id, created_at)
-- INDEX idx_stock_mov_type_date (type, created_at)
-- INDEX idx_stock_mov_reference (reference_type, reference_id)

-- =========================================================
-- ops_categoria
-- Source: src/modules/categories/category.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- nombre VARCHAR(140) NOT NULL
-- nombre_normalized VARCHAR(140) NOT NULL UNIQUE
-- estado VARCHAR(20) NOT NULL DEFAULT 'activo'
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_categoria_estado (estado)

-- =========================================================
-- ops_proveedores
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- id INT AUTO_INCREMENT PRIMARY KEY
-- nombre VARCHAR(140) NOT NULL UNIQUE
-- telefono VARCHAR(60) NULL
-- email VARCHAR(190) NULL
-- dias_pedido_csv VARCHAR(80) NULL
-- dias_entrega_csv VARCHAR(80) NULL
-- estado VARCHAR(20) NOT NULL DEFAULT 'activo'
-- notas VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_proveedor_estado (estado)

-- =========================================================
-- ops_producto (extension)
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- supplier_id INT NULL
-- categoria_id INT NULL
-- INDEX idx_producto_supplier_id (supplier_id)
-- INDEX idx_producto_categoria_id (categoria_id)
-- FOREIGN KEY (categoria_id) REFERENCES ops_categoria(id) ON DELETE SET NULL

-- =========================================================
-- ops_supplier_orders
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- supplier_id INT NOT NULL
-- order_date DATE NOT NULL
-- delivery_date DATE NOT NULL
-- expected_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- status VARCHAR(20) NOT NULL DEFAULT 'pendiente'
-- notes VARCHAR(255) NULL
-- operator_id INT NULL
-- operator_name VARCHAR(140) NULL
-- operator_role VARCHAR(20) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_supplier_orders_delivery_status (delivery_date, status)
-- INDEX idx_supplier_orders_supplier_delivery (supplier_id, delivery_date)

-- =========================================================
-- ops_supplier_order_items
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- order_id BIGINT NOT NULL
-- product_id INT NULL
-- product_name VARCHAR(190) NOT NULL
-- quantity DECIMAL(12,3) NOT NULL DEFAULT 1
-- unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- notes VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_supplier_order_items_order (order_id)
-- INDEX idx_supplier_order_items_product (product_id)
-- FOREIGN KEY (order_id) REFERENCES ops_supplier_orders(id) ON DELETE CASCADE

-- =========================================================
-- ops_supplier_order_drafts
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- supplier_id INT NOT NULL
-- status VARCHAR(20) NOT NULL DEFAULT 'open'
-- source VARCHAR(30) NOT NULL DEFAULT 'stock'
-- notes VARCHAR(255) NULL
-- operator_id INT NULL
-- operator_name VARCHAR(140) NULL
-- operator_role VARCHAR(20) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_supplier_drafts_supplier_status (supplier_id, status)
-- INDEX idx_supplier_drafts_updated (updated_at)
-- FOREIGN KEY (supplier_id) REFERENCES ops_proveedores(id) ON DELETE CASCADE

-- =========================================================
-- ops_supplier_order_draft_items
-- Source: src/modules/suppliers/supplier.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- draft_id BIGINT NOT NULL
-- product_id INT NULL
-- product_name VARCHAR(190) NOT NULL
-- quantity DECIMAL(12,3) NOT NULL DEFAULT 1
-- unit_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- source VARCHAR(30) NOT NULL DEFAULT 'stock_alert'
-- notes VARCHAR(255) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_supplier_draft_items_draft (draft_id)
-- INDEX idx_supplier_draft_items_product (product_id)
-- UNIQUE KEY uniq_supplier_draft_product (draft_id, product_id)
-- FOREIGN KEY (draft_id) REFERENCES ops_supplier_order_drafts(id) ON DELETE CASCADE

-- =========================================================
-- ops_web_usuarios
-- Source: src/modules/webAuth/webAuth.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- nombre VARCHAR(140) NOT NULL
-- nombre_normalized VARCHAR(140) NOT NULL UNIQUE
-- email VARCHAR(190) NOT NULL UNIQUE
-- role VARCHAR(30) NOT NULL DEFAULT 'cliente'
-- password_salt VARCHAR(128) NOT NULL
-- password_hash VARCHAR(255) NOT NULL
-- estado VARCHAR(20) NOT NULL DEFAULT 'activo'
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_web_usuarios_estado (estado)

-- =========================================================
-- ops_web_usuario_perfil
-- Source: src/modules/webUsers/webUsers.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- web_usuario_id BIGINT NOT NULL UNIQUE
-- telefono VARCHAR(40) NULL
-- direccion_base VARCHAR(255) NULL
-- notas_admin VARCHAR(255) NULL
-- puntos_actuales INT NOT NULL DEFAULT 0
-- puntos_acumulados INT NOT NULL DEFAULT 0
-- nivel_fidelidad VARCHAR(20) NOT NULL DEFAULT 'base'
-- total_compras INT NOT NULL DEFAULT 0
-- monto_total_compras DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- ultima_compra_at DATETIME NULL
-- login_count INT NOT NULL DEFAULT 0
-- last_login_at DATETIME NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_web_usuario_perfil_puntos (puntos_actuales)
-- INDEX idx_web_usuario_perfil_login (last_login_at)
-- FOREIGN KEY (web_usuario_id) REFERENCES ops_web_usuarios(id) ON DELETE CASCADE

-- =========================================================
-- ops_web_usuario_eventos
-- Source: src/modules/webUsers/webUsers.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- web_usuario_id BIGINT NOT NULL
-- event_type VARCHAR(40) NOT NULL
-- metadata_json LONGTEXT NULL
-- event_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- INDEX idx_web_usuario_eventos_user_date (web_usuario_id, event_at)
-- INDEX idx_web_usuario_eventos_type_date (event_type, event_at)
-- FOREIGN KEY (web_usuario_id) REFERENCES ops_web_usuarios(id) ON DELETE CASCADE

-- =========================================================
-- ops_web_puntos_movimientos
-- Source: src/modules/webUsers/webUsers.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- web_usuario_id BIGINT NOT NULL
-- pedido_id BIGINT NULL
-- tipo VARCHAR(20) NOT NULL
-- puntos INT NOT NULL
-- saldo_posterior INT NOT NULL
-- motivo VARCHAR(120) NULL
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- INDEX idx_web_puntos_user_date (web_usuario_id, created_at)
-- INDEX idx_web_puntos_pedido (pedido_id)
-- FOREIGN KEY (web_usuario_id) REFERENCES ops_web_usuarios(id) ON DELETE CASCADE

-- =========================================================
-- ops_web_pedidos
-- Source: src/modules/webOrders/webOrders.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- web_usuario_id BIGINT NOT NULL
-- estado VARCHAR(20) NOT NULL DEFAULT 'nuevo'
-- notas VARCHAR(255) NULL
-- total_estimado DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_web_pedidos_estado_fecha (estado, created_at)
-- INDEX idx_web_pedidos_usuario_fecha (web_usuario_id, created_at)
-- FOREIGN KEY (web_usuario_id) REFERENCES ops_web_usuarios(id) ON DELETE CASCADE

-- =========================================================
-- ops_web_pedido_items
-- Source: src/modules/webOrders/webOrders.repository.js
-- =========================================================
-- id BIGINT AUTO_INCREMENT PRIMARY KEY
-- pedido_id BIGINT NOT NULL
-- product_id INT NOT NULL
-- product_name VARCHAR(190) NOT NULL
-- quantity INT NOT NULL DEFAULT 1
-- unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00
-- created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- INDEX idx_web_pedido_items_pedido (pedido_id)
-- INDEX idx_web_pedido_items_product (product_id)
-- FOREIGN KEY (pedido_id) REFERENCES ops_web_pedidos(id) ON DELETE CASCADE
